name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install & Build
      run: |
        npm install
        npm run build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.6.0
      with:
        branch: gh-pages
        folder: dist

       